### ISSUE TITLE
AttributeError: 'NoneType' object has no attribute 'pause'

### ISSUE THREAD

**Issue by landybird** [gaogaotiantian/viztracer#42]
`AttributeError: 'NoneType' object has no attribute 'pause'` occured
while using decorator `ignore_function`  as [decuments ignore_function](https://viztracer.readthedocs.io/en/stable/advanced_usage.html) suggested.

It seemd that the default tracer was not initialized. And if I pass a tracer  as param into ignore_function it worked well.

```python
from viztracer import VizTracer, ignore_function

@ignore_function
def f():
    n = 0
    for i in range(1, 100):
        for o in range(1, 20):
            n += (i+0)
    print(n)

with VizTracer(max_stack_depth=3, ignore_c_function=True):
    f()

```

traceback error:

```
Traceback (most recent call last):
  File "C:/Users/PycharmProjects/oneway_test/test.py", line 12, in <module>
    f()
  File "D:\virtual\Envs\venv37\lib\site-packages\viztracer\decorator.py", line 17, in ignore_wrapper
    tracer.pause()
AttributeError: 'NoneType' object has no attribute 'pause'

```

I'm working with `python3.7.7` and platform is `[MSC v.1900 64 bit (AMD64)] on win32`

**Comment by gaogaotiantian** [comment]
This is a valid bug. The cause is a commit a couple of days ago when I tried to avoid direct call to the underlay structure. 

```@ignore_function``` needs a tracer object now, and it will try to read the undocumented ```global_tracer``` first, which will be set if viztracer is executed through command line. 

For now, passing the tracer into ```@ignore_function``` could be the temporary solution. I will work on some utilities to register global tracer explicitly because this might not be the only case where a function requires the tracer.

**Comment by gaogaotiantian** [comment]
I realized that I actually documented in the decorator API that ```@ignore_function``` should only be used without arguments from command line, but I forgot to mention it in the general introduction. However, I made this work with inline usage as well in #43. If you still have issues, please tell me and reopen this.
